### ISSUE TITLE
Magic link button does not appear when using Safari

### ISSUE THREAD

**Issue by waisaed** [galahq/gala#642]
When inviting students to a group, the magic link does not appear when viewed in Safari

**Comment by timothyf** [comment]
Ed, can you provide more detail around this issue?   Ideally, steps on how I can reproduce this.

**Comment by timothyf** [comment]
Nevermind, I just updated the Asana issue with my reproduction of the issue.

**Comment by timothyf** [comment]
This is fixed and pushed to production.

**Comment by cbothner** [comment]
Hey, sorry to swoop back in here uninvited. 94e4715b3058cac2218885d22d4aee0f94e66e1c had the unintended consequence of making the `TitleCard`s on the front page weirdly tall or cut off, since that component is shared between the magic link view and the catalog.

<img width="1343" alt="Screen Shot 2020-01-22 at 6 29 36 PM" src="https://user-images.githubusercontent.com/4642599/72943902-481b2e00-3d45-11ea-920e-0d2f5fe4e209.png">
<img width="994" alt="Screen Shot 2020-01-22 at 6 34 28 PM" src="https://user-images.githubusercontent.com/4642599/72944070-dc859080-3d45-11ea-8044-f7a0d8987311.png">

What about this patch instead?
```diff
diff --git app/javascript/shared/TitleCard.jsx app/javascript/shared/TitleCard.jsx
index d1a74a76..9f3eb059 100644
--- app/javascript/shared/TitleCard.jsx
+++ app/javascript/shared/TitleCard.jsx
@@ -133,6 +133,10 @@ export const Container = styled.div`
     border-radius: 3px;
   }

+  ${MagicLinkContainer} & {
+    height: unset;
+  }
+
   ${SidebarContainer} & {
     border-radius: 3px;
     border-bottom: 4px solid #6ACB72;

```

Ping @timothyf @waisaed

**Comment by timothyf** [comment]
Cameron,

Good to hear from you again. You might remember me still from when we met
in person almost a year ago it seems.  I appreciate your pointing this out
to me. I will take a look at your suggested patch and likely proceed with
that.

Thanks,
Tim

**Comment by timothyf** [comment]
Okay, I have applied the patch suggested by Cameron, tested it locally to confirm it, and have deployed.

**Comment by cbothner** [comment]
Definitely remember you, Tim! Glad to know you're there supporting the MSC team :)
